#load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library", "rust_test")
#
#rust_library(
#    name = "error_lib",
#    srcs = [
#        "src/error.rs",
#    ],
#    visibility = ["//visibility:public"],
#)
#
#rust_test(
#    name = "error_lib_tests",
#    srcs = [
#        "tests/tests.rs",
#    ],
#    deps = [
#        ":error_lib",
#    ],
#)
