# TODO: Activate back when Rust is a valid toolchain again.
#load("//libs/bzl/build_test:build_test.bzl", "build_test")
#load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary", "rust_library", "rust_test")
#
#rust_binary(
#    name = "p4_snippets",
#    srcs = [
#        "src/main.rs",
#    ],
#    deps = [
#        "@chrono",
#        "@clipboard_win",
#        "@getopts",
#    ],
#)
