# TODO: Activate back when Rust is a valid toolchain.
#load("//libs/bzl/build_test:build_test.bzl", "build_test")
#load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary")
#
#rust_binary(
#    name = "incredible",
#    srcs = [
#        "src/main.rs",
#    ],
#)
