# TODO: Activate back when Rust is a valid toolchain.
#load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary")
#
#rust_binary(
#    name = "rust_cleaner",
#    srcs = [
#        "src/main.rs",
#    ],
#    deps = [
#        "//libs/rust/error_lib",
#    ],
#)
