#load("@io_bazel_rules_rust//rust:rust.bzl", "rust_binary", "rust_library", "rust_test")
#
#rust_binary(
#    name = "p4_main",
#    srcs = [
#        "src/main.rs",
#        "tests/test.rs",
#    ],
#    deps = [
#        ":p4_lib",
#    ],
#)
#
#rust_library(
#    name = "p4_lib",
#    srcs = [
#        "src/lib.rs",
#    ],
#    deps = [
#        "//libs/rust/error_lib",
#        "@lazy_static",
#        "@regex",
#    ],
#)
#
#rust_test(
#    name = "p4_lib_tests",
#    srcs = [
#        "tests/test.rs",
#    ],
#    deps = [
#        ":p4_lib",
#        "//libs/rust/error_lib",
#    ],
#)
